# Cloudflare Pages 배포 설정
name = "hqmx-converter"
compatibility_date = "2024-01-15"

# Pages 프로젝트 설정
pages_build_output_dir = "dist"

# 환경 변수 설정
[env.production.vars]
ENVIRONMENT = "production"
VERSION = "2.0.0"

[env.preview.vars]
ENVIRONMENT = "preview"
VERSION = "2.0.0-preview"

# 빌드 설정
[build]
command = "npm run build"
cwd = ""
watch_dir = "src"

# Wrangler 설정
[wrangler]
send_metrics = false